# Cours "Traitement informatique des données"
### Louis Maritaud
### louis.maritaud@unilim.fr

## Objectifs pédagogiques
- Traiter des données réelles

## Pour ce cours
Nous allons travailler sur le fichier `DATA/LifeExpectancy.csv`, que l'on va manipuler avec Pandas. Vous allez faire toutes les démarches et manipulations les unes après les autres. 

## PREMIERE ETAPE 
### Lecture et nettoyage du fichier

In [ ]:
# Importez pandas

# Votre code ici


# Ouvrez le fichier

# Votre code ici


# On regarde à quoi ça ressemble, des données réelles 

# Votre code ici

**Solution**

In [47]:
import pandas as pd 

df = pd.read_csv("DATA/LifeExpectancy.csv", encoding="utf-8")

display(df)

,ccode,country name,1500,1501,1502,1503,1504,1505,1506,1507,...,2041,2042,2043,2044,2045,2046,2047,2048,2049,2050
0,4.0,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8.0,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,12.0,Algeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20.0,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,24.0,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,862.0,Venezuela,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,704.0,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
195,887.0,Yemen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,894.0,Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,716.0,Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Des remarques sur ce fichier ? 
- Comment est-il construit ? 
- Quelles sont les lignes / colonnes ?
- Combien de lignes / colonnes ?
- Remarques libres ?

# On peut modifier simplement les données dans ce tableau pour le rendre exploitable
La fonction pd.melt()

In [62]:
# On "fond" le tableau en colonnes
df_long = pd.melt(
    df,
    id_vars=["ccode", "country name"],  # Les colonnes qu'on garde intactes
    var_name="year",  # Le nom de la nouvelle colonne pour les en-têtes (les années)
    value_name="life_expectancy",  # Le nom de la colonne pour les valeurs
)

# On convertit l'année en nombre entier (car melt la laisse en texte/objet)
df_long["year"] = df_long["year"].astype(int)

# On nettoie les lignes sans données
df_long = df_long.dropna(subset=["life_expectancy"])

df_long.info()
print(sorted(list(set(df_long["country name"]))))
display(df_long)

<class 'pandas.core.frame.DataFrame'>
Index: 12863 entries, 8702 to 101558
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ccode            12863 non-null  float64
 1   country name     12863 non-null  object
 2   year             12863 non-null  int64
 3   life_expectancy  12863 non-null  float64
dtypes: float64(2), int64(1), object(1)
memory usage: 502.5+ KB
['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 'Congo, DRC', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Lithuania', 'Luxembourg', 'Macedonia', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Moldova', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Korea', 'Norway', 'Oman', 'Pakistan', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda', 'Samoa', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Is.', 'Somalia', 'South Africa', 'South Korea', 'Spain', 'Sri Lanka', 'St. Lucia', 'St. Vincent and the Grenadines', 'Suriname', 'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'Tajikistan', 'Tanzania', 'Thailand', 'The Gambia', 'Timor Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe']

        ccode    country name  year  life_expectancy
8702    826.0  United Kingdom  1543            33.94
9692    826.0  United Kingdom  1548            38.82
10682   826.0  United Kingdom  1553            39.59
11672   826.0  United Kingdom  1558            22.38
12662   826.0  United Kingdom  1563            36.66
...       ...             ...   ...              ...
101360  792.0          Turkey  2011            74.60
101366  826.0  United Kingdom  2011            80.80
101367  840.0   United States  2011            78.70
101486  484.0          Mexico  2012            74.40
101558  792.0          Turkey  2012            74.60

[12863 rows x 4 columns]

# Consignes
Vous avez le choix entre :
- Choisir un jeu de données qui vous appartient ou que vous trouverez en igne (Nakala, Recherche Data Gouv), et le manipuler avec Python et ce qu'on a vu
- Rester sur le jeu de données fourni, et le manipuler avec Python et ce qu'on a vu :
    * Pistes :
        * **1- Analyse longitudinale d'un pays :** Trouver les valeurs minimales et maximales ; calculer la moyenne sur toutes les années ; éventuellement faire une courbe avec matplotlib ; essayer de trouver des explications aux données
        * **2- Analyse synchronique d'une année :** Pour tous les pays disposant d'une valeur à une année x : calculer la moyenne sur tous les pays, trouver les valeurs minimales et maximales, essayer de trouver des explications aux données 
        * **3- Analyse par "zone géographique" :** Pour tous les pays d'une zone (ie Europe, espace Schengen, Asie du Sud-Ouest), produire les mêmes résultats qu'au dessus
        * **4- Analyse par "événement" :** Pour tous les pays dépendant d'un événement (ie WW2), produire les mêmes résultats qu'au dessus 

Ce travail constituera votre rendu final. L'idée est de produire des résultats sur la base de l'espérance de vie par année, et d'en faire un commentaire. 

# Sauvegarde et rendu
Pour sauvegarder le notebook :     
- File > Save and export notebook as 
Pour sauvegarder des fichers : 
- Les sauvegarder via Python, puis clic droit dessus dans le panneau à gauche > Download